layout_spectrum: 0.2658303
color:
  saturation: 0.5895098
  lightness: 0.7161384
  brandStrength: 0.42911
  rhythmicContrast: 0.6221755
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
typography_spectrum: 0.9098234
name: Fotus
