layout_spectrum: 0.2658303
color:
  saturation: 0.318399
  brandStrength: 0.42911
  lightness: 0.6409796
  brandColors:
    - '#323949'
    - '#BFB4B0'
    - '#99857E'
    - '#F0E8DE'
    - '#547360'
  rhythmicContrast: 0.4223417
typography_spectrum: 0.9098234
name: Fotus
