layout_spectrum: 0.2658303
color:
  saturation: 0.5382317
  brandStrength: 0.8142174
  lightness: 0.6314217
  brandColors:
    - '#323949'
    - '#BFB4B0'
    - '#99857E'
    - '#F0E8DE'
    - '#547360'
  rhythmicContrast: 0.6194743
typography_spectrum: 0.4199522
name: Fotus
navigation:
  - name: I am fotus.
    id: ae05aabd-e641-4e6c-8dd8-d4fe254d272e
    type: content
